name: complex
version: 0.0.2
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A representation of a complex number, i.e. a number which has both a real and imaginary part.
homepage: https://github.com/rwl/complex
dependencies:
  unittest: any
